//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitAutoCommit.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitAutoCommit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Committing changes to {0}.
        /// </summary>
        internal static string AutoCommitHandler__timer_Elapsed_Committing_changes {
            get {
                return ResourceManager.GetString("AutoCommitHandler__timer_Elapsed_Committing_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Synchronizing untracked changes in {0} ....
        /// </summary>
        internal static string AutoCommitHandler_OnConfigurationChange_Synchronizing_untracked_changes {
            get {
                return ResourceManager.GetString("AutoCommitHandler_OnConfigurationChange_Synchronizing_untracked_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Synchronizing untracked changes.
        /// </summary>
        internal static string AutoCommitHandler_OnConfigurationChange_Synchronizing_untracked_changes_commit {
            get {
                return ResourceManager.GetString("AutoCommitHandler_OnConfigurationChange_Synchronizing_untracked_changes_commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný add task.
        /// </summary>
        internal static string EditTaskForm_Bind_add_task {
            get {
                return ResourceManager.GetString("EditTaskForm_Bind_add_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Automatic commit.
        /// </summary>
        internal static string EditTaskForm_Bind_Automatic_commit {
            get {
                return ResourceManager.GetString("EditTaskForm_Bind_Automatic_commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Please enter a valid folder.
        /// </summary>
        internal static string EditTaskForm_FormIsValid_Please_enter_a_valid_folder {
            get {
                return ResourceManager.GetString("EditTaskForm_FormIsValid_Please_enter_a_valid_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný The selected folder doesn&apos;t seem to be a git repository.
        /// </summary>
        internal static string EditTaskForm_FormIsValid_The_selected_folder_doesnt_seem_to_be_a_git_repository {
            get {
                return ResourceManager.GetString("EditTaskForm_FormIsValid_The_selected_folder_doesnt_seem_to_be_a_git_repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Icon podobný (Ikona).
        /// </summary>
        internal static System.Drawing.Icon icon_16 {
            get {
                object obj = ResourceManager.GetObject("icon_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32 {
            get {
                object obj = ResourceManager.GetObject("icon_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 1 hour.
        /// </summary>
        internal static string Interval_1_hour {
            get {
                return ResourceManager.GetString("Interval_1_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 1 minute.
        /// </summary>
        internal static string Interval_1_minute {
            get {
                return ResourceManager.GetString("Interval_1_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný 1 second.
        /// </summary>
        internal static string Interval_1_second {
            get {
                return ResourceManager.GetString("Interval_1_second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0} hours.
        /// </summary>
        internal static string Interval_hours {
            get {
                return ResourceManager.GetString("Interval_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0} minutes.
        /// </summary>
        internal static string Interval_minutes {
            get {
                return ResourceManager.GetString("Interval_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný {0} seconds.
        /// </summary>
        internal static string Interval_seconds {
            get {
                return ResourceManager.GetString("Interval_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &amp;Configuration.
        /// </summary>
        internal static string NotifyIconController_NotifyIconController_Configuration {
            get {
                return ResourceManager.GetString("NotifyIconController_NotifyIconController_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný E&amp;xit.
        /// </summary>
        internal static string NotifyIconController_NotifyIconController_Exit {
            get {
                return ResourceManager.GetString("NotifyIconController_NotifyIconController_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Git auto commit.
        /// </summary>
        internal static string NotifyIconController_NotifyIconController_Git_auto_commit {
            get {
                return ResourceManager.GetString("NotifyIconController_NotifyIconController_Git_auto_commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Directory {0} doesn&apos;t exist.
        /// </summary>
        internal static string Program_AllDirectoriesExist_Directory_doesnt_exist {
            get {
                return ResourceManager.GetString("Program_AllDirectoriesExist_Directory_doesnt_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Directory {0} is not a git repository.
        /// </summary>
        internal static string Program_AllDirectoriesExist_Directory_is_not_a_git_repository {
            get {
                return ResourceManager.GetString("Program_AllDirectoriesExist_Directory_is_not_a_git_repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný git-auto-commit.
        /// </summary>
        internal static string Program_Main_git_auto_commit {
            get {
                return ResourceManager.GetString("Program_Main_git_auto_commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Invalid command line arguments.
        /// </summary>
        internal static string Program_Main_Invalid_command_line_arguments {
            get {
                return ResourceManager.GetString("Program_Main_Invalid_command_line_arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný usage: git-auto-commit &lt;commit-interval-seconds&gt; &lt;directory 1&gt;, &lt;directory 2&gt;, ..., &lt;directory n&gt;.
        /// </summary>
        internal static string Program_Main_usage {
            get {
                return ResourceManager.GetString("Program_Main_usage", resourceCulture);
            }
        }
    }
}
